<?php
/**
 *
 * Date: 21.10.2021
 * Time: 10:37
 *
 */
namespace Pimcorecasts\Bundle\QrCode\Installer;

use Pimcore\Model\DataObject;
use Pimcore\Extension\Bundle\Installer\AbstractInstaller;
use Pimcore\Extension\Bundle\Installer\SettingsStoreAwareInstaller;
use Symfony\Component\DependencyInjection\ParameterBag\ContainerBagInterface;


class Installer extends AbstractInstaller
{

    /**
     * @var ContainerBagInterface|null
     */
    private $params;


    public function getMigrationVersion(): string
    {
        return 'Version20211201000000';
    }


    public function __construct(ContainerBagInterface $params = null) {
        $this->params = $params;
        parent::__construct();
    }

    public function install(){


    }


    public function uninstall()
    {
        parent::uninstall(); // TODO: Change the autogenerated stub
    }

    /**
     * @return bool
     */
    public function needsReloadAfterInstall()
    {
        return true;
    }

    /**
     * @return bool
     */
    public function isInstalled()
    {
        $isInstalled = true;

        // Check if all Classes and Bricks are installed
        if (
            !DataObject\ClassDefinition::getByName('QrCode') ||

            !DataObject\Objectbrick::getByName('QrLocation') ||
            !DataObject\Objectbrick::getByName('QrUrl') ||
            !DataObject\Objectbrick::getByName('QrVCard')
        ) {
            $isInstalled = false;
        }

        return $isInstalled;
    }



}
