services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pimcorecasts\Bundle\QrCodeBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: [ 'controller.service_arguments' ]

    Pimcorecasts\Bundle\QrCodeBundle\Installer\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('PimcorecastsQrCodeBundle')"

# Services
    Pimcorecasts\Bundle\QrCodeBundle\Services\QrDataService:
        public: true

#    Pimcorecasts\Bundle\QrCode\Service\:
#        resource: '../../Service'
#        public: true