services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pimcorecasts\Bundle\QrCode\Controller\:
        resource: '../../Controller'
        public: true
        tags: [ 'controller.service_arguments' ]

    Pimcorecasts\Bundle\QrCode\Installer\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('QrCodeBundle')"

# Services
    Pimcorecasts\Bundle\QrCode\Services\QrDataService:
        public: true

# LinkGenerator
    Pimcorecasts\Bundle\QrCode\LinkGenerator\QrCodeLinkGenerator:
        public: true

# Slug Service
    Pimcorecasts\Bundle\QrCode\Services\UrlSlugResolver:
        public: true

# Options Provider
    Pimcorecasts\Bundle\QrCode\OptionsProvider\DownloadSizeOptionsProvider:
        public: true


#    Pimcorecasts\Bundle\QrCode\Service\:
#        resource: '../../Service'
#        public: true